moved keycloak starting check to appleboy ssh

diff --git a/.github/workflows/cd_deployment.yml b/.github/workflows/cd_deployment.yml
--- a/.github/workflows/cd_deployment.yml
+++ b/.github/workflows/cd_deployment.yml
@@ -220,32 +220,26 @@ jobs:
           envs: CONTAINER_NAME
           script: |
             echo "Waiting for Keycloak to start..."
+            # Function to check Keycloak readiness
+            function wait_for_keycloak_ready() {
+              MAX_RETRIES=30
+              SLEEP_TIME=10
+              URL="http://localhost:80/health/ready"
+              #URL="http://localhost:80/realms/master/.well-known/openid-configuration"
+              RETRIES=0
+              until [[ $(curl -s -o /dev/null -w '%{http_code}' $URL) == 200 ]]; do
+                RETRIES=$((RETRIES+1))
+                if [ "$RETRIES" -ge "$MAX_RETRIES" ]; then
+                  echo "Keycloak readiness check failed after $RETRIES retries. Exiting."
+                  exit 1
+                fi
+                echo "Waiting for Keycloak to be ready... ($RETRIES/$MAX_RETRIES)"
+                sleep $SLEEP_TIME
+              done
+            }
+            # Call the function to wait for Keycloak to be ready
+            wait_for_keycloak_ready
         timeout-minutes: 5
-
-      - name: Wait for Keycloak to be ready
-        run: |
-          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << EOF
-          # Function to check Keycloak readiness
-          function wait_for_keycloak_ready() {
-            MAX_RETRIES=30
-            SLEEP_TIME=10
-            URL="http://localhost:80/health/ready"
-            #URL="http://localhost:80/realms/master/.well-known/openid-configuration"
-            RETRIES=0
-            until [[ $(curl -s -o /dev/null -w '%{http_code}' $URL) == 200 ]]; do
-              RETRIES=$((RETRIES+1))
-              if [ "$RETRIES" -ge "$MAX_RETRIES" ]; then
-                echo "Keycloak readiness check failed after $RETRIES retries. Exiting."
-                exit 1
-              fi
-              echo "Waiting for Keycloak to be ready... ($RETRIES/$MAX_RETRIES)"
-              sleep $SLEEP_TIME
-            done
-          }
-
-          # Call the function to wait for Keycloak to be ready
-          wait_for_keycloak_ready
-
 
       - name: Add realm-admin for terraform client
         uses: appleboy/ssh-action@v1.1.0
